version: '3.8'

services:

  db:
    image: postgres
    container_name: postgredb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
      - ./create_db.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - 5432:5432

volumes:
  db:
    driver: local
